@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include DEVICONS/python.puml
!include FONTAWESOME/database.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/check.puml
!include FONTAWESOME/server.puml


HIDE_STEREOTYPE()


System(begin, "Scorevision Cli")
System(sv_api, "Scorevision API")
System(r2, "Cloudflare R2",  $sprite="database")
System(bt, "Bittensor", "On-Chain Commit")

Boundary(push, "Push", "Miners") {
    System(hf, "Huggingface Hub", "Create/Update/Verify Repo with ML Model Weights")
    System(chute, "Chutes", "Build & Deploy ML Model")
    System(warmup, "Warmup", "Call ML Model")
}

Boundary(vali, "[Validators]") {
  Boundary(runner, "Runner") {
      System(ch, "Process Challenge", "Mp4 to B64, Dense Optical Flow, Frame Sampling, etc")
      System(vlm1, "VLM Annotator", "Generate Pseudo-GT")
      System(miner, "Chutes", "Call ML Model")
      System(metrics, "Metrics", "Pseudo-GT vs ML Model")
  }
  Boundary(validate, "Validate") {
    System(weights, "Update weights")
  }
}

Rel_R(begin, push, "ml_model_path or hf_revision")
Rel_D(begin, runner, "chute slug")
Rel_D(begin, validate, "tail, alpha, ...")


Rel_R(vlm1, metrics, "pseudo-GT")
Rel_D(sv_api, ch, "challenge")
Rel_D(ch, miner, " ")
Rel_R(ch, vlm1, " ")
Rel_R(miner, metrics, " ")
Rel_D(metrics, r2, " ")

Rel_R(hf, chute, "hf_revision")
Rel_R(chute, warmup, "chute slug")
Rel_D(chute,bt, "chute id & slug")

Rel_L(r2, weights, " ")
Rel_U(weights, bt, "weights")
@enduml